spring.datasource.url=jdbc:mysql://localhost:3306/bookmyshowdb?createTableIfNotExists=true
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adityasinghraj0405@gmail.com
spring.mail.password=Aditya_1108
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

api.base-url-for-data=https://api.themoviedb.org/3
api.base-url-for-poster=https://image.tmdb.org/t/p/w200
api.api-key=f5779d58304b2779aeeb2f8b8a55daaa